spring: 
  datasource:
    url: jdbc:postgresql://postgresdb:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  cache:
    cache-names: cartToken, productToken, profileToken, publicToken
    caffeine:
      spec: expireAfterAccess=1800s
  security:
    ouath2:
      client:
        registration:
          kroger:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: cart.basic:write
        provider:
          kroger:
            authorization-uri: https://api.kroger.com/v1/connect/oauth2/authorize


kroger:
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}